Libris cli
ieugen/clj-nexus-api-client pull request #2
Opened 2023-10-29 09:29 UTC by sandre1

2023-10-29 09:43 UTC, ieugen requested changes

2023-10-29 09:43 UTC, ieugen commented on src/nexus_api_client/cli.clj
> +(defn remove-internal-meta
Asta este relevantă pentru APi-ul nostru?

2023-10-29 09:43 UTC, ieugen commented on src/nexus_api_client/cli.clj
> +(defn remove-internal-meta
nexus nu cred că are "contajners"

2023-10-29 09:43 UTC, ieugen commented on src/nexus_api_client/cli.clj
> +(defn doc
url e hardcodat !!

2023-10-29 09:43 UTC, ieugen commented on src/nexus_api_client/cli.clj
> +(defn invoke
Sunt funcții aici care nu țin de CLI. 
Ar trebui separate în ns-ul lor. 

Ai API clojure.
Ai api CLI care folosește API clojure să expună interfața clojure în CLI.
Mai putem avea API rest care face același lucru - ca serviciu REST.
etc.

2023-10-29 09:43 UTC, ieugen commented on src/nexus_api_client/cli.clj
> +(defn usage [options-summary]
Asta este clar API CLI, cea de mai sus nu este.

2023-10-29 09:43 UTC, ieugen commented on src/nexus_api_client/cli.clj
> +(defn delete-image [cfg image]
APi-ul tău CLI este foarte direcționat către Docker.
Nexus știe mai multe tipuri de artefacte: https://help.sonatype.com/repomanager3/nexus-repository-administration/formats .

Poate ar fi bine să ții cont de asta în cod (în nume)  ?!

2023-10-30 10:15 UTC, sandre1 commented on src/nexus_api_client/cli.clj
> +(defn doc
am modificat sa citeasca url din config

2023-10-30 10:22 UTC, sandre1 commented on src/nexus_api_client/cli.clj
> +(defn usage [options-summary]
am separat api cli de api clojure

2023-11-01 08:33 UTC, ieugen approved these changes

2023-11-01 08:33 UTC, merged